### ISSUE TITLE
Adding maker functional annotation

### ISSUE THREAD

**Issue by okendojo** [schellt/maker-functional#1]
I am trying your scripts and I have not been able to update the functional annotation and meta-data in my maker gff file. Do you have the idea on how to change the gene names in maker gff to gene symbols which are human readable? 

I my maker I have names like `Name=genemark-ptg000079l-abinit-gene-0.14-mRNA-1` but this are not making sense to me.

**Comment by schellt** [comment]
Hi Javan,
thanks for considering my scripts.
The `name=` tag in gff files is more an ID than a function. You can infer information on GO terms, pathways and more e.g. with InterProScan, Blast2GO or by blasting the protein sequences to a database like SwissProt.
The scripts here are just to transfer this information to the gff and fasta files respectively, not to conduct functional annotation.
